name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - run: npm install

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run type-check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish (main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm publish --workspaces --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
