name: Publish to GitHub Packages

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@aokiapp"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Add branch suffix to version (if not main/master)
        id: version
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$GITHUB_REF" == refs/heads/main || "$GITHUB_REF" == refs/heads/master ]]; then
            echo "No suffix needed for main/master"
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          else
            # Sanitize branch name for npm version
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr -cd '[:alnum:]-')
            # Get current version
            VERSION=$(node -p "require('./package.json').version")
            # Append suffix
            NEW_VERSION="${VERSION}-${SAFE_BRANCH}"
            npm version --no-git-tag-version "$NEW_VERSION"
            echo "SUFFIX=$SAFE_BRANCH" >> $GITHUB_OUTPUT
          fi

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com/
